name: digitalme
region: nyc

services:
  - name: backend
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3001
    routes:
      - path: /api
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3001"

  - name: frontend
    source_dir: /
    github:
      branch: main
      deploy_on_push: true
    build_command: npm run build
    output_dir: build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
